In [1]:
from matplotlib.axes._axes import _log as matplotlib_axes_logger
import pandas as pd
import seaborn as sns
%matplotlib inline
import numpy as np
from math import sqrt
from sqlalchemy import create_engine
import psycopg2


sns.set_context('talk')

matplotlib_axes_logger.setLevel('ERROR')

In [38]:
def create_target(df_original):
    df = df_original.copy()
    y = df['sitrep_cible']
    del df['sitrep_cible']
    # Remplacer les valeurs manquantes par la moyenne
    df = df.fillna(df.mean())
    return df, y

def load_visits(engine, history):
    ## Ce sont des résumés de visites avec le nombre de prescriptions
    return pd.read_sql("select * from visite_securite".format(history), engine)

def load_sitrep(engine):
    return pd.read_sql("select * from sitrep".format(history), engine)

def load_navire(engine):
    ## Ce sont des résumés de visites avec le nombre de prescriptions
    return pd.read_sql("select id_nav_flotteur, annee_construction, genre_navigation, longueur_hors_tout from navire".format(history), engine)

def load_history(engine, history=5):
    return pd.read_sql("select \"annee\", \"prescriptions\", \"prescriptions_majeurs\", \"at\", \"genre_navigation\", \"longueur_hors_tout\", \"sitrep\", \"sitrep_cible\" from dataset_{}".format(history), engine)

# Downloading data

In [39]:
engine = create_engine('postgresql://postgres:password@localhost/cibnav')
history = load_history(engine)
visits = load_visits(create_engine('postgresql://postgres:password@localhost/cibnav'), 10)
visits = visits.fillna(0)
navires = load_navire(engine)
sitreps = load_sitrep(engine)

In [40]:
df = pd.merge(left=visits, right=navires, left_on='id_nav_flotteur', right_on='id_nav_flotteur')

# Applying some transformations

In [41]:
df['year_visit'] = df['date_visite'].apply(lambda date_visite: date_visite.year)

A ce stade, une ligne correspond a une visite de sécurité. On ajoute l'historique des sitrep

In [42]:
# On ordonne nos données pour pouvoir utiliser les fonctions suivantes
df = df.set_index(['id_nav_flotteur', 'date_visite'])
df = df.sort_index()
df = df.reset_index()

In [43]:
def previous_sitrep(row, sitreps):
    navire = row['id_nav_flotteur']
    previous_year = row['date_visite'].year
    return sitreps[(sitreps['id_nav_flotteur'] == navire) & (sitreps['annee'] <= previous_year)]['sitrep'].sum()

df['sitrep_history'] = df.apply(lambda row: previous_sitrep(row, sitreps), axis=1)

Puis le délai entre deux visites de sécurité

In [44]:
def add_date_time_between_visit(df):
    df_time = df.copy()
    df_time['delai_visites'] = df_time['date_visite'].diff()
    df_time['checkindex'] = df_time['id_nav_flotteur'].diff() 
    
    # The diff function will apply to all the visits. We will only consider the lines where the vessel is the same (id_nav_flotteur - id_nav_flotteur == 0)
    df_time['delai_visites'] = df_time.apply(lambda row: row['delai_visites'].days if row['checkindex'] == 0 else np.nan, axis=1)
    del df_time['checkindex']
    return df_time

df = add_date_time_between_visit(df)

Enfin, nous ajoutons l'historique des prescriptions et des prescriptions majeures grâce à une loi de décroissance.
`feature_moyenne_prescriptions_suite = 1*P1 + P2/2 + P3/3/ (1 + 1/2 + 1/3)`

In [45]:
# On une série des prescriptions en entrée
# On veut la même série avec une moyenne cumulative
def decreasing_mean(presc):
    presc_list = presc.to_list()
    presc_mean= {}
    try:
        for i, val in enumerate(presc_list):
            if i > 0:
                presc_mean[i] = np.mean(presc_list[:i])
            else:
                presc_mean[i] = val
        return pd.Series(presc_mean)
    except TypeError as e:
        return presc

def add_prescriptions_history(df):
    df_prescr_hist = df.copy()
    for presc in ['nombre_prescriptions', 'nombre_prescriptions_majeurs']:
        col_name = '{}_hist'.format(presc)
        df_prescr_hist[col_name] = df_prescr_hist.groupby('id_nav_flotteur')[presc].transform(decreasing_mean)
    return df_prescr_hist

df = add_prescriptions_history(df)
df

,id_nav_flotteur,date_visite,id_gin_visite,nombre_prescriptions,nombre_prescriptions_majeurs,annee_construction,genre_navigation,longueur_hors_tout,year_visit,sitrep_history,delai_visites,nombre_prescriptions_hist,nombre_prescriptions_majeurs_hist
0,3774.0,2012-03-13 00:00:00+01:00,43598,0.0,0.0,1971.0,Petite pêche,6.03,2012,0,NaN,0.0,0.0
1,3774.0,2013-03-07 00:00:00+01:00,53472,0.0,0.0,1971.0,Petite pêche,6.03,2013,0,359.0,0.0,0.0
2,3774.0,2014-03-19 00:00:00+01:00,67934,0.0,0.0,1971.0,Petite pêche,6.03,2014,0,377.0,0.0,0.0
3,3774.0,2015-03-11 00:00:00+01:00,80052,0.0,0.0,1971.0,Petite pêche,6.03,2015,0,357.0,0.0,0.0
4,3774.0,2016-03-10 00:00:00+01:00,92531,1.0,0.0,1971.0,Petite pêche,6.03,2016,0,365.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72446,1864788.0,2019-06-18 00:00:00+02:00,133679,1.0,1.0,2001.0,None,7.30,2019,0,NaN,1.0,1.0
72447,1864798.0,2019-07-23 00:00:00+02:00,133906,1.0,0.0,2005.0,None,6.15,2019,0,NaN,1.0,0.0
72448,1864816.0,2019-10-09 00:00:00+02:00,135797,1.0,1.0,2018.0,None,11.75,2019,0,NaN,1.0,1.0
72449,1866833.0,2020-01-14 00:00:00+01:00,138465,0.0,0.0,2012.0,None,7.50,2020,0,NaN,0.0,0.0
72450,1877208.0,2019-09-05 00:00:00+02:00,134799,0.0,0.0,2004.0,None,8.63,2019,0,NaN,0.0,0.0

In [46]:
df.describe()

,id_nav_flotteur,id_gin_visite,nombre_prescriptions,nombre_prescriptions_majeurs,annee_construction,longueur_hors_tout,year_visit,sitrep_history,delai_visites,nombre_prescriptions_hist,nombre_prescriptions_majeurs_hist
count,7.245100e+04,72451.000000,72451.000000,72451.000000,72451.000000,72451.000000,72451.000000,72451.000000,57944.000000,72451.000000,72451.000000
mean,1.255097e+06,72384.663635,1.321776,0.216960,1992.515963,13.455175,2014.058453,2.092518,527.395209,0.368037,0.056246
std,1.927504e+05,37302.306905,2.883913,0.659052,12.938783,16.394881,3.095801,7.770242,359.236297,1.394703,0.240257
min,3.774000e+03,10000.000000,0.000000,0.000000,1896.000000,2.920000,1996.000000,0.000000,0.000000,0.000000,0.000000
25%,1.227513e+06,39945.500000,0.000000,0.000000,1984.000000,7.250000,2012.000000,0.000000,363.000000,0.000000,0.000000
50%,1.236105e+06,70544.000000,0.000000,0.000000,1993.000000,9.470000,2014.000000,0.000000,376.000000,0.000000,0.000000
75%,1.243181e+06,105098.500000,1.000000,0.000000,2003.000000,14.000000,2017.000000,0.000000,509.000000,0.000000,0.000000
max,1.877208e+06,138693.000000,46.000000,13.000000,2019.000000,365.500000,2020.000000,350.000000,7274.000000,41.000000,6.000000

# Cleaning data

- We know that the maximum number of days between two visits should be 1825 (==5 year). Let s remove all the lines with more than 2000 days.

- The 'nombre de prescriptions' et 'nombre_prescriptions_majeures' are clean.

In [37]:
df[df['sitrep_history'] > 30]

,id_nav_flotteur,date_visite,id_gin_visite,nombre_prescriptions,nombre_prescriptions_majeurs,annee_construction,genre_navigation,year_visit,sitrep_history,delai_visites,nombre_prescriptions_hist,nombre_prescriptions_majeurs_hist
3420,1201883.0,2019-05-21 00:00:00+02:00,131538,0.0,0.0,1973.0,Navigation côtière,2019,50,398.0,1.700000,0.300000
5432,1205811.0,2018-03-27 00:00:00+02:00,117099,3.0,0.0,1975.0,Navigation côtière,2018,40,364.0,1.555556,0.555556
5433,1205811.0,2019-03-05 00:00:00+01:00,128452,2.0,1.0,1975.0,Navigation côtière,2019,50,343.0,1.700000,0.500000
5751,1206883.0,2016-10-21 00:00:00+02:00,100752,2.0,1.0,1971.0,Petite pêche,2016,35,387.0,0.000000,0.000000
5752,1206883.0,2017-10-18 00:00:00+02:00,112377,3.0,0.0,1971.0,Petite pêche,2017,35,362.0,0.285714,0.142857
...,...,...,...,...,...,...,...,...,...,...,...,...
68395,1680258.0,2018-03-12 00:00:00+01:00,116476,3.0,0.0,1991.0,Cabotage Internat.,2018,85,349.0,2.333333,0.000000
68396,1680258.0,2019-03-21 00:00:00+01:00,129274,4.0,1.0,1991.0,Cabotage Internat.,2019,85,374.0,2.428571,0.000000
68863,1699326.0,2019-07-10 00:00:00+02:00,133451,5.0,1.0,2014.0,Petite pêche,2019,35,363.0,1.750000,0.500000
71419,1789700.0,2018-02-23 00:00:00+01:00,115530,5.0,2.0,2002.0,Cabotage Internat.,2018,35,266.0,1.500000,0.500000
71420,1789700.0,2019-02-08 00:00:00+01:00,127704,6.0,0.0,2002.0,Cabotage Internat.,2019,35,350.0,2.666667,1.000000

In [49]:
print("Avant suppression des extremes de longueur : {} lignes".format(len(df)))
df = df[df.longueur_hors_tout < 24]
print("Après suppression des extremes de longueur (> 24 et nan) : {} lignes".format(len(df)))

Avant suppression des extremes de longueur : 52271 lignes
Après suppression des extremes de longueur (> 24 et nan) : 52271 lignes

In [52]:
print("Avant suppression des extremes de delai visites : {} lignes".format(len(df)))
df = df[df.delai_visites < 2000]
print("Après suppression des extremes de delai visites (> 2000 et nan) : {} lignes".format(len(df)))
print("Ce filtre supprime les premières visites")

Avant suppression des extremes de delai visites : 52271 lignes
Après suppression des extremes de delai visites (> 2000 et nan) : 52271 lignes
Ce filtre supprime les premières visites

In [54]:
df.to_csv('dataset_visites.csv', sep=';')

In [142]:
# def previous_visit(row, df):
#     date_visite = row['date_visite']
#     navire = row.id_nav_flotteur
#     visites = df[df.id_nav_flotteur == navire].copy()
    
#     visits['last_visit'] = visits['date_visite'].shift(1)
    
#     time_since_previous_visit = date_visite - visits[visits['date_visite'] == date_visite].last_visit
#     return time_since_previous_visit